# Site
name: Tech Forever
description: A Modern UI Platform
meta_description: "Technology and Gadgets - News, Views, Opinions & Mobile Reviews | Gadgets & Gizmos | Video & Photo Reviews at OnHub."
logo: 'assets/images/onhub.png'
favicon: 'assets/images/logo1.png'
paginate: 15
baseurl: /
google_analytics: 'UA-114581196-1'
disqus: 'ooioo'
mailchimp-list: 'https://onhub.us17.list-manage.com/subscribe/post?u=d8d0df5a1f1778f865840b939&amp;id=b002547450'

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  kd:
    name: kd
    display_name: Admin
    gravatar: 5a621643b01a4f99239190d5c6aec450
    email: xy@datamail.in
    web: http://www.onhub.me
    twitter: https://twitter.com/gpaidapps
    description: "Author of OnHub, Who is involving UI delivery for readers."
    
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
    
# Archives
jekyll-archives:
  enabled:
    - categories
    - jekyll
    - tutorial
    - news
    - trending
  layout: archive
  permalinks: pretty
    
    
    
# Other
markdown: kramdown
highlighter: rouge

exclude: [node_modules, README.md]
